[package]
name = "terminalwiki-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
terminalwiki-core = { workspace = true }
terminalwiki-index = { workspace = true }
terminalwiki-render = { workspace = true }
terminalwiki-graph = { workspace = true }
terminalwiki-tui = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
